### ISSUE TITLE
Update linkmod to the new mod portal

### ISSUE THREAD

**Issue by tzwaan** [arielbeje/uBot#18]
Anyone up for an update?

**Comment by SuperSandro2000** [comment]
I'll try to fix it. The website parsing should probably be replaced with some api in the long run but I am not motivated to do that right now.

Edit: The new css classes are not great.
Edit2: I think I got it working again.
![image](https://user-images.githubusercontent.com/7258858/89076647-ff41d300-d380-11ea-94fa-d22ec2d62b3c.png)
@tzwaan

**Comment by tzwaan** [comment]
>The website parsing should probably be replaced with some api in the long run

That would be great, were it not that the mod portal api does not have proper search functionality.
